export const ActionTypes = {
  FETCH_LATEST: "FETCH_LATEST",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  SEARCH_NEWS: "SEARCH_NEWS",
  FETCH_COUNTRIES: "FETCH_COUNTRIES",
  SELECT_COUNTRY: " SELECT_COUNTRY",
  GET_TOKEN: "GET_TOKEN",
  SET_USER: "SET_USER",
  USER_LOGOUT: "USER_LOGUT",
  SET_ERROR: "SET_ERROR",
  START_LOADING: "START_LOADING",
  END_LOADING: "END_LOADING",
};
