export const ActionTypes = {
  //news
  NEWS_LOADING: "NEWS_LOADING",
  FETCH_LATEST: "FETCH_LATEST",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  SEARCH_NEWS: "SEARCH_NEWS",
  //country
  FETCH_COUNTRIES: "FETCH_COUNTRIES",
  SELECT_COUNTRY: "SELECT_COUNTRY",
  //auth
  USER_LOADING: "USER_LOADING",
  GET_TOKEN: "GET_TOKEN",
  SET_USER: "SET_USER",
  USER_LOGOUT: "USER_LOGUT",
  //firestore
  FIRESTORE_LOADING: "FIRESTORE_LOADING",
  GET_SAVED_NEWS: "GET_SAVED_NEWS",
  //ui
  OPEN_SNACKBAR: "OPEN_SNACKBAR",
  CLOSE_SNACKBAR: "CLOSE_SNACKBAR",
  SET_ERROR: "SET_ERROR",
  OPEN_LOGIN: "OPEN_LOGIN",
  CLOSE_LOGIN: "CLOSE_LOGIN",
  OPEN_SIGNUP: "OPEN_SIGNUP",
  CLOSE_SIGNUP: "CLOSE_SIGNUP",
};
